### ISSUE TITLE
Failed to build on debian 11

### ISSUE THREAD

**Issue by marek22k** [chris2511/xca#374]
Steps:
Install the dependencies 
Clone
Configure
failed to make
```
$cmake --build build -j8
[  5%] Automatic MOC and UIC for target core
[ 12%] Built target translations
[ 12%] Automatic MOC and UIC for target widgets
[ 12%] Built target core_autogen
[ 12%] Built target widgets_autogen
[ 72%] Built target core
[ 73%] Built target widgets
[ 74%] Automatic MOC and UIC for target xcadoc
[ 74%] Built target xcadoc_autogen
[ 76%] Built target xcadoc
[ 78%] Built target manpage
[ 78%] Prepare Sphinx source directory
[ 79%] Built target sphinx-src
[ 81%] Create context sensitive help
[ 81%] Create HTML documentation
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 33, in <module>
    sys.exit(load_entry_point('Sphinx==3.4.3', 'console_scripts', 'sphinx-build')())
  File "/usr/bin/sphinx-build", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/usr/lib/python3/dist-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/usr/lib/python3/dist-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/bandura/.local/lib/python3.9/site-packages/jinja2/__init__.py)
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 33, in <module>
    sys.exit(load_entry_point('Sphinx==3.4.3', 'console_scripts', 'sphinx-build')())
  File "/usr/bin/sphinx-build", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/usr/lib/python3/dist-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/usr/lib/python3/dist-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/bandura/.local/lib/python3.9/site-packages/jinja2/__init__.py)
gmake[2]: *** [CMakeFiles/sphinx-qthelp.dir/build.make:91: doc/qthelp/xca.qhcp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:271: CMakeFiles/sphinx-qthelp.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/sphinx-html.dir/build.make:89: doc/html/index.html] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:245: CMakeFiles/sphinx-html.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

**Comment by marek22k** [comment]
works with downgrading a python tool: `pip3 install Jinja2==3.0.3`

**Comment by chris2511** [comment]
Maybe mixing apt and pip as installation source is the cause.
Why not installing jinja2 via apt?
```
$ apt show python3-jinja2
Package: python-jinja2
Version: 2.11.3-1
```
At least that's what I did and it works fine.
